//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOOKUP
    {
        public string LOOKUP_TYPE { get; set; }
        public string LOOKUP_CODE { get; set; }
        public string MEANING { get; set; }
    }
}
