//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDERCART
    {
        public int ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> OLD_PRICE { get; set; }
        public Nullable<int> PROMOTION_ID { get; set; }
    
        public virtual T_ORDER T_ORDER { get; set; }
    }
}
