//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDER
    {
        public T_ORDER()
        {
            this.T_ORDERCART = new HashSet<T_ORDERCART>();
        }
    
        public int ORDERID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> SHIPPINGMETHOD { get; set; }
        public string PAYMENTTYPE { get; set; }
        public string ORDERSTATUS { get; set; }
        public Nullable<decimal> SHIPPINGCOST { get; set; }
        public Nullable<decimal> ORDERDISCOUNT { get; set; }
        public string CUSTOMERIP { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<System.DateTime> PAYMENTDATE { get; set; }
        public string CUSTOMERCOMMENT { get; set; }
        public string SHIPPINGNAME { get; set; }
        public string SHIPPINGPROVINCE { get; set; }
        public string SHIPPINGAMPHUR { get; set; }
        public string SHIPPINGDISTRICT { get; set; }
        public string SHIPPINGPOSTCODE { get; set; }
        public string SHIPPINGADDRESS1 { get; set; }
        public string SHIPPINGEMAIL { get; set; }
        public string SHIPPINGTEL { get; set; }
        public string SHIPPINGFAX { get; set; }
        public string BILLINGNAME { get; set; }
        public string BILLINGPROVINCE { get; set; }
        public string BILLINGAMPHUR { get; set; }
        public string BILLINGDISTRICT { get; set; }
        public string BILLINGPOSTCODE { get; set; }
        public string BILLINGADDRESS1 { get; set; }
        public string BILLINGEMAIL { get; set; }
        public string BILLINGTEL { get; set; }
        public string BILLINGFAX { get; set; }
        public string PAYMENTNUMBER { get; set; }
        public string SHIPPINGADDRESS2 { get; set; }
        public string SHIPPINGADDRESS3 { get; set; }
        public string SHIPPINGADDRESS4 { get; set; }
        public string SHIPPINGMOBILE { get; set; }
        public string BILLINGADDRESS2 { get; set; }
        public string BILLINGADDRESS3 { get; set; }
        public string BILLINGADDRESS4 { get; set; }
        public string CUSTOMERNAME { get; set; }
    
        public virtual T_SHIPPINGMETHOD T_SHIPPINGMETHOD { get; set; }
        public virtual ICollection<T_ORDERCART> T_ORDERCART { get; set; }
    }
}
