//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCTS_ATT
    {
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int CATEGORIES_ATT_ID { get; set; }
        public string DESCR_TH { get; set; }
        public string DESCR_EN { get; set; }
        public short ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string DELETE_BY { get; set; }
    
        public virtual T_CATEGORIES_ATT T_CATEGORIES_ATT { get; set; }
        public virtual T_PRODUCTS T_PRODUCTS { get; set; }
    }
}
