//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROMOTION
    {
        public T_PROMOTION()
        {
            this.T_PROMOTION_CONDITION = new HashSet<T_PROMOTION_CONDITION>();
            this.T_PROMOTION_EXCLUDE = new HashSet<T_PROMOTION_EXCLUDE>();
        }
    
        public int ID { get; set; }
        public string PROMO_NAME_TH { get; set; }
        public string PROMO_DESC_TH { get; set; }
        public short ACTIVE { get; set; }
        public Nullable<int> CUSTOMER_GROUP { get; set; }
        public short COUPON { get; set; }
        public string COUPON_CODE { get; set; }
        public Nullable<int> USER_PER_COUPON { get; set; }
        public Nullable<int> USER_PER_CUSTOMER { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<short> PUBLIC_IN_RSS_FEED { get; set; }
        public string APPLY { get; set; }
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
        public Nullable<int> MAX_QTY_DISCOUNT_IS_APPLIED_TO { get; set; }
        public Nullable<int> DISCOUNT_QTY_STEP { get; set; }
        public Nullable<decimal> APPLY_TO_SHIPPING_AMOUNT { get; set; }
        public Nullable<short> FREE_SHIPPING { get; set; }
        public string MAX_QTY_PER_EACH { get; set; }
        public Nullable<System.TimeSpan> PROMO_START_TIME { get; set; }
        public Nullable<System.TimeSpan> PROMO_END_TIME { get; set; }
        public Nullable<int> USE_COUNT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string DELETE_BY { get; set; }
        public string PROMO_NAME_EN { get; set; }
        public string PROMO_DESC_EN { get; set; }
        public string PROMOTION_TYPE { get; set; }
    
        public virtual ICollection<T_PROMOTION_CONDITION> T_PROMOTION_CONDITION { get; set; }
        public virtual ICollection<T_PROMOTION_EXCLUDE> T_PROMOTION_EXCLUDE { get; set; }
    }
}
