//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCTS
    {
        public T_PRODUCTS()
        {
            this.T_PRODUCT_RELATION = new HashSet<T_PRODUCT_RELATION>();
            this.T_ONHAND = new HashSet<T_ONHAND>();
            this.T_PRODUCTS_ATT = new HashSet<T_PRODUCTS_ATT>();
        }
    
        public int ID { get; set; }
        public string NAME_TH { get; set; }
        public string NAME_EN { get; set; }
        public string DESCR_TH { get; set; }
        public string DESCR_EN { get; set; }
        public int CATEGORIES_ID { get; set; }
        public string PRODUCT_SKU { get; set; }
        public int VENDOR_ID { get; set; }
        public decimal COST { get; set; }
        public decimal PRICE { get; set; }
        public short ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string DELETE_BY { get; set; }
        public string SHORT_DESCR_TH { get; set; }
        public string SHORT_DESCR_EN { get; set; }
        public Nullable<decimal> OLD_PRICE { get; set; }
        public short BUY_FLAG { get; set; }
        public short WISH_LIST { get; set; }
        public short CALL_PRICE_FLAG { get; set; }
        public short SHIPPING_FLAG { get; set; }
        public decimal SHIPPING_CHARGE { get; set; }
        public decimal TAX_VALUE { get; set; }
        public string TAX_TYPE { get; set; }
        public decimal MIN_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public decimal STOCK_QTY { get; set; }
        public short DISPLAY_QTY_FLAG { get; set; }
        public Nullable<decimal> MIN_STOCK_QTY { get; set; }
        public Nullable<short> NEW_ARRIVAL_FLAG { get; set; }
        public int BRAND_ID { get; set; }
        public Nullable<short> RECOMMEND_FLAG { get; set; }
        public Nullable<decimal> WEIGTH { get; set; }
    
        public virtual T_BRAND T_BRAND { get; set; }
        public virtual T_CATEGORIES T_CATEGORIES { get; set; }
        public virtual ICollection<T_PRODUCT_RELATION> T_PRODUCT_RELATION { get; set; }
        public virtual ICollection<T_ONHAND> T_ONHAND { get; set; }
        public virtual ICollection<T_PRODUCTS_ATT> T_PRODUCTS_ATT { get; set; }
        public virtual T_VENDOR T_VENDOR { get; set; }
    }
}
