//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SHIPPINGMETHOD
    {
        public T_SHIPPINGMETHOD()
        {
            this.T_ORDER = new HashSet<T_ORDER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string DELETE_BY { get; set; }
    
        public virtual ICollection<T_ORDER> T_ORDER { get; set; }
    }
}
