//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCTS
    {
        public int ID { get; set; }
        public string NAME_TH { get; set; }
        public string NAME_EN { get; set; }
        public string DESCR_TH { get; set; }
        public string DESCR_EN { get; set; }
        public int CATEGORIES_ID { get; set; }
        public int BRAND_ID { get; set; }
        public string CATEGORY_EN { get; set; }
        public string PRODUCT_SKU { get; set; }
        public string VENDOR_EN { get; set; }
        public decimal COST { get; set; }
        public Nullable<decimal> OLD_PRICE { get; set; }
        public decimal PRICE { get; set; }
        public string BRAND_EN { get; set; }
        public decimal ONHAND { get; set; }
        public short BUY_FLAG { get; set; }
        public short WISH_LIST { get; set; }
        public short CALL_PRICE_FLAG { get; set; }
        public short SHIPPING_FLAG { get; set; }
        public decimal SHIPPING_CHARGE { get; set; }
        public decimal TAX_VALUE { get; set; }
        public string TAX_TYPE { get; set; }
        public decimal MIN_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public decimal STOCK_QTY { get; set; }
        public short DISPLAY_QTY_FLAG { get; set; }
        public Nullable<decimal> MIN_STOCK_QTY { get; set; }
        public Nullable<short> NEW_ARRIVAL_FLAG { get; set; }
        public Nullable<short> RECOMMEND_FLAG { get; set; }
        public Nullable<decimal> WEIGTH { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public short ACTIVE { get; set; }
    }
}
