//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCT_CATAGORIES
    {
        public int P_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int ID { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_TH { get; set; }
        public string P_NAME_EN { get; set; }
        public string P_NAME_TH { get; set; }
        public short ACTIVE { get; set; }
    }
}
