//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ROLE_PROGRAM
    {
        public string NAME { get; set; }
        public string DESC { get; set; }
        public int ID { get; set; }
        public Nullable<int> RANK { get; set; }
        public string TYPE { get; set; }
        public int ROLE_ID { get; set; }
        public string PRIVILEGE { get; set; }
    }
}
