//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiffyOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_ROLES
    {
        public int ID { get; set; }
        public string name_th { get; set; }
        public string name_en { get; set; }
        public string AUTH_USER { get; set; }
        public string AUTH_PASS { get; set; }
        public string EMAIL { get; set; }
        public int role_id { get; set; }
        public string role_name { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
    }
}
